theme: jekyll-theme-minimal
title: The Open Class 3D Exchange (OCX) ocx-rudder-extension schema
description: The OCX organisation is an open standardisation initiative promoting the OCX standard (a neutral XML format) as an interoperability standard between ship designers/yards and classification societies.
